export { default as Navbar } from './Navbar'
export { default as Homepage } from './Homepage'
export { default as News } from './News'
export { default as Cryptocurrencies } from './Cryptocurrencies'
export { default as Forex } from './Forex'
export { default as Stocks } from './Stocks'
export { default as Watchlist } from './Watchlist'
